#!/usr/bin/env python3
"""
The energy division multiplexing channel plan, computed.

Chooses interconnect channels for multi unit machines (theory Section
10.4): each transmitting unit modulates a sealed source whose emission
lines are its channel; the receiving unit's spectroscopic boundary
separates channels by energy window. This script computes, for standard
catalog sources and two detector classes, the pairwise separations,
Gaussian window leakage, and channel longevity, and writes the plan to
edm_channels.md.

Resolution model (stated, simple, adequate): FWHM(E) = a * sqrt(E),
anchored at 662 keV: 2 percent for CZT, 7 percent for NaI.
"""
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# line keV, source, half life (y), companion line of the same source
LINES = [
    (59.5, "241Am", 432.0, None),
    (122.1, "57Co", 0.74, "136.5 keV (11%)"),
    (356.0, "133Ba", 10.5, "81.0 keV (33%)"),
    (511.0, "22Na", 2.60, "1274.5 keV (one per decay)"),
    (661.7, "137Cs", 30.1, None),
    (834.8, "54Mn", 0.85, None),
    (1115.5, "65Zn", 0.67, None),
    (1173.2, "60Co", 5.27, "1332.5 keV (one per decay)"),
    (1274.5, "22Na*", 2.60, "companion of 511"),
    (1332.5, "60Co*", 5.27, "companion of 1173"),
]

DETECTORS = [("CZT", 0.02), ("NaI", 0.07)]


def fwhm(E, frac662):
    a = frac662 * 661.7 / math.sqrt(661.7)
    return a * math.sqrt(E)


def leakage(E_from, E_into, frac662):
    """Fraction of line E_from's Gaussian falling inside E_into's
    +-1 FWHM acceptance window."""
    s = fwhm(E_from, frac662) / 2.3548
    w = fwhm(E_into, frac662)
    lo, hi = E_into - w, E_into + w
    def cdf(x):
        return 0.5 * (1 + math.erf((x - E_from) / (s * math.sqrt(2))))
    return cdf(hi) - cdf(lo)


def main():
    out = []

    def say(s=""):
        out.append(s)
        print(s)

    say("# The EDM channel plan (regenerated by edm_plan.py)\n")
    say("Channels for multi unit interconnect: one modulated source per "
        "transmitting unit, one energy window per receiving port "
        "(theory Section 10.4). Companion lines of the same source "
        "modulate together and are free redundant copies of their "
        "channel, usable as parity. Resolution model: FWHM = a sqrt(E), "
        "anchored 2 percent (CZT) and 7 percent (NaI) at 662 keV.\n")

    primaries = [l for l in LINES if not l[1].endswith("*")]

    for det, frac in DETECTORS:
        say(f"## {det} boundary\n")
        say("| line (keV) | source | t1/2 (y) | FWHM (keV) | nearest "
            "line | separation / FWHM | worst window leakage |")
        say("|---|---|---|---|---|---|---|")
        usable = 0
        for E, src, t, comp in primaries:
            others = [l for l in LINES if l[0] != E]
            nearest = min(others, key=lambda l: abs(l[0] - E))
            sep = abs(nearest[0] - E)
            f_here = fwhm(E, frac)
            worst = max(leakage(l[0], E, frac) for l in others)
            ok = sep / f_here >= 2.0 and worst < 0.05
            usable += ok
            say(f"| {E} | {src} | {t:g} | {f_here:.1f} | "
                f"{nearest[1]} ({nearest[0]}) | {sep/f_here:.1f} | "
                f"{worst:.1%}{'' if ok else '  **crowded**'} |")
        say(f"\n**{usable} of {len(primaries)} channels clean** "
            "(separation at least 2 FWHM and leakage under 5 percent).\n")

    say("## Longevity note\n")
    say("Channel sources age like everything else here, and the plan "
        "says so: ⁵⁷Co, ⁵⁴Mn, and ⁶⁵Zn are annual consumables; ²²Na and "
        "⁶⁰Co are five year parts; ¹³³Ba is a decade part; ¹³⁷Cs and "
        "²⁴¹Am are the mission grade channels. A long mission rack "
        "should carry its high traffic links on ²⁴¹Am, ¹³⁷Cs, ¹³³Ba, "
        "and ⁶⁰Co, and treat the rest as replaceable patch cables. By "
        "degree homogeneity (theory Section 7), channel aging costs "
        "link bandwidth, never link correctness, provided both ends "
        "ratio against the same line.\n")

    open(os.path.join(HERE, "edm_channels.md"), "w").write("\n".join(out))
    print("wrote gates/edm_channels.md")


if __name__ == "__main__":
    main()
