# Copyright 2026 Max Freedom Pollard
# SPDX-License-Identifier: Apache-2.0
"""Every relative link and image in the documents points at a file that
exists. The repository cross references itself hundreds of times; a renamed
directory or figure must not leave a dead link behind."""
import os
import re

from conftest import ROOT, read, tracked

LINK = re.compile(r"!?\[[^\]]*\]\(([^)\s]*[./#][^)\s]*)\)")     # a target with a slash, a dot or an anchor: not the (x) of B_n[f](x)


def test_every_relative_link_and_image_resolves():
    dead = []
    for p in tracked(".md"):
        base = os.path.dirname(os.path.join(ROOT, p))
        for target in LINK.findall(read(p)):
            if target.startswith(("http://", "https://", "mailto:", "#")):
                continue
            path = target.split("#")[0]
            if not path:
                continue
            if not os.path.exists(os.path.normpath(os.path.join(base, path))):
                dead.append((p, target))
    assert not dead, f"dead links: {dead}"


def test_every_figure_the_documents_show_is_regenerated_by_a_script():
    shown = set()
    for p in tracked(".md"):
        for target in LINK.findall(read(p)):
            if target.endswith(".svg") and "figures/" in target:
                shown.add(os.path.basename(target))
    scripts = "\n".join(read(p) for p in tracked(".py"))
    orphans = sorted(s for s in shown if s[:-4] not in scripts and s != "fig1_architecture.svg")
    assert not orphans, f"figures shown but not generated by any script: {orphans}"
