#!/usr/bin/env python3
# Copyright 2026 Max Freedom Pollard
# SPDX-License-Identifier: Apache-2.0
"""
The neutron gate, reported: derived quantities, the checks, results.md,
and figure 15, all from tallies.json and benchmarks.json.

Needs only numpy and matplotlib, so it runs in the ordinary CI job on the
committed tally files; gate.py and benchmarks.py, which need OpenMC and
the data library, regenerate those files.

Derived here and nowhere else:
  the gain M = 1/(1 - k) of each tank and of the pair in every absorber
  state; the fission matrix K, its dominant eigenvalue against the
  transport k, and the unsplit bank control (the exactness check of the
  synapse with gain); the point model (I - K)^-1 c against the full
  fixed source transport, and what the gap between them means; the
  transistor and coincidence truth tables with their margins; the neutron
  budget of a fission neutron born in tank A (the fan out tax); the
  emission spectra under three different drives against the spectra that
  arrived (level restoration); the generation time, the switching time,
  the gain bandwidth product, and the step response of the pair by prompt
  point kinetics; and the temperature coefficient that prices the veto.
"""
import json
import math
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
FIGS = os.path.join(os.path.dirname(HERE), "figures")
OUT = []
STATES = [("open", "open"), ("cd", "1 mm cadmium sheet"), ("b4c", "2 cm boron carbide blade")]


def say(s=""):
    OUT.append(s)


def pm(v, digits=4):
    return f"{v[0]:.{digits}f} ± {v[1]:.{digits}f}"


def gain(k):
    m = 1.0 / (1.0 - k[0])
    return [m, k[1] * m * m]


def region(run, tag, score):
    return run["regions"][tag][score]


def fission_matrix(runs, state):
    K = np.zeros((2, 2)); S = np.zeros((2, 2))
    for j, tag in enumerate("AB"):
        r = runs[f"coupling_{tag}_{state}"]
        for i, out in enumerate("AB"):
            K[i, j], S[i, j] = region(r, out, "nu-fission")
    return K, S


def dominant(K, S, n=4000, seed=229):
    rng = np.random.default_rng(seed)
    lam = np.linalg.eigvals(K).real.max()
    samples = [np.linalg.eigvals(K + rng.normal(0, 1, K.shape) * S).real.max() for _ in range(n)]
    return lam, float(np.std(samples))


def vec2(run):
    return (np.array([region(run, "A", "nu-fission")[0], region(run, "B", "nu-fission")[0]]),
            np.array([region(run, "A", "nu-fission")[1], region(run, "B", "nu-fission")[1]]))


def spectrum(run, name, edges):
    """Normalised per unit lethargy, the mean energy (eV), and the fraction
    below 0.625 eV."""
    m = np.array(run[name]["mean"])
    tot = m.sum()
    if tot <= 0:
        return np.zeros_like(m), float("nan"), 0.0
    mid = np.sqrt(edges[:-1] * edges[1:])
    return m / tot / np.log(edges[1:] / edges[:-1]), float((m * mid).sum() / tot), float(m[mid < 0.625].sum() / tot)


def step_response(K, c, Lambda, t_end, n=3000):
    """Prompt point kinetics of the pair, Λ dP/dt = (K - I) P + c, driver on
    at t = 0, integrated exactly through the eigen decomposition."""
    A = (K - np.eye(2)) / Lambda
    b = c / Lambda
    w, V = np.linalg.eig(A)
    Vinv = np.linalg.inv(V)
    Pinf = np.linalg.solve(-A, b)
    ts = np.linspace(0, t_end, n)
    P = np.array([(Pinf - (V @ np.diag(np.exp(w * t)) @ Vinv @ Pinf)).real for t in ts])
    return ts, P, Pinf


def main():
    doc = json.load(open(os.path.join(HERE, "tallies.json")))
    runs, prov = doc["runs"], doc["provenance"]
    bench = json.load(open(os.path.join(HERE, "benchmarks.json")))
    edges = np.array(prov["model"]["energy_edges_eV"])
    model = prov["model"]
    label = dict(STATES)

    say("# The neutron gate, computed (regenerated by report.py from tallies.json and benchmarks.json)\n")
    say(f"OpenMC {prov['openmc_version']}, {prov['library']}, budget {prov['budget']} "
        f"({prov.get('wall_clock_minutes', '?')} minutes of wall clock). Every number carries its "
        "Monte Carlo standard deviation; nothing is fitted.\n")

    # ---- 0. calibration ---------------------------------------------------
    say("## 0. Calibration: the instrument against the handbook\n")
    say("| benchmark | this code and data | handbook | difference from handbook (pcm) | JEFF-3.1 on the same case | difference from JEFF-3.1 (pcm) |")
    say("|---|---|---|---|---|---|")
    for key, c in bench["cases"].items():
        k, kb, kj = c["k"], c["benchmark"], c["jeff31"]
        d = (k[0] - kb[0]) * 1e5
        sig = math.sqrt(k[1] ** 2 + kb[1] ** 2) * 1e5
        dj = (k[0] - kj[0]) * 1e5
        sigj = math.sqrt(k[1] ** 2 + kj[1] ** 2) * 1e5
        say(f"| {key} | {pm(k, 5)} | {kb[0]:.5f} ± {kb[1]:.5f} | {d:+.0f} ± {sig:.0f} | "
            f"{kj[0]:.5f} | {dj:+.0f} ± {sigj:.0f} |")
    say("\nGodiva is the fast spectrum and the fission cross sections alone; SHEBA-II is the thermal "
        "spectrum, the water scattering law, and the gate's own material family (uranyl fluoride "
        "solution); STACY is a water reflected solution tank, the configuration of the gate. The "
        "JEFF-3.1 column, from the same table as the handbook values (JEFF Report 21, Appendix 2), is "
        "carried because it separates a fault in this calculation from a fault in the benchmark. "
        "Godiva and STACY land where a modern library should. SHEBA-II is overpredicted here by about "
        "a percent, and JEFF-3.1 overpredicts it by the same amount from the same specification: this "
        "benchmark is known to sit high for every modern library, and a calculation that agrees with "
        "its peers to a few hundred pcm while both disagree with the experiment is reporting a "
        "property of the evaluation, not an error in the model. The gate below is a difference "
        "between configurations of one geometry, where that common bias very largely cancels; the "
        "absolute eigenvalues it quotes should be read with SHEBA-II's percent in mind.\n")

    # ---- 1. the unit alone ------------------------------------------------
    say("## 1. The unit alone\n")
    say(f"One tank: radius {model['R_tank_cm']:.0f} cm, height {model['H_tank_cm']:.0f} cm, "
        f"{math.pi*model['R_tank_cm']**2*model['H_tank_cm']/1000:.0f} litres of 4.9 percent enriched "
        "uranyl fluoride solution (the LEU-SOL-THERM-002 benchmark composition) in a 1.6 mm aluminium "
        f"shell, standing in {model['reflector_cm']:.0f} cm of water on every side.\n")
    say("| tank | k (alone) | gain M = 1/(1 - k) | generation time Λ (µs) | β | switching time Λ/(1 - k) (ms) | gain bandwidth product 1/Λ (kHz) |")
    say("|---|---|---|---|---|---|---|")
    for tag in "AB":
        r = runs[f"alone_{tag}"]
        k = r["k"]; M = gain(k)
        L = r["global"]["inverse-velocity"][0] / r["global"]["nu-fission"][0]
        beta = region(r, tag, "delayed-nu-fission")[0] / region(r, tag, "nu-fission")[0]
        say(f"| {tag} | {pm(k, 4)} | {pm(M, 2)} | {L*1e6:.1f} | {beta:.4f} | {L*M[0]*1e3:.2f} | {1/L/1e3:.1f} |")
    say("\nΛ is the system generation time, neutron population over fission neutron production, "
        "reflector included; β is the delayed neutron fraction from the tallies (not β effective). "
        "The switching time is the prompt time constant Λ/(1 - k) of the transistor note, and M "
        "times its reciprocal is the constant 1/Λ: the op amp law, with laboratory grade constants in it.\n")

    # ---- 2. coupled -------------------------------------------------------
    say("## 2. The pair, with the absorber as the GATE terminal\n")
    say("| configuration | k (pair) | gain M | fission share in B (0.500 by symmetry: see 3.1) | entropy, last 20 percent of active batches |")
    say("|---|---|---|---|---|")
    curve = []
    for name, desc in (("coupled_open", "open, 3 cm of water"),
                       ("coupled_cd25", "cadmium sheet 25 percent in"),
                       ("coupled_cd50", "cadmium sheet 50 percent in"),
                       ("coupled_cd75", "cadmium sheet 75 percent in"),
                       ("coupled_cd", "cadmium sheet fully in"),
                       ("coupled_b4c", "boron carbide blade fully in")):
        r = runs[name]
        k = r["k"]; M = gain(k)
        share = region(r, "B", "nu-fission")[0] / (region(r, "A", "nu-fission")[0] + region(r, "B", "nu-fission")[0])
        ent = r.get("entropy", [])
        drift = f"{np.mean(ent[-len(ent)//5:]):.3f} ± {np.std(ent[-len(ent)//5:]):.3f}" if ent else "n/a"
        curve.append((name, k, M))
        say(f"| {desc} | {pm(k, 4)} | {pm(M, 2)} | {share:.3f} | {drift} |")
    k_open, k_cd, k_b4c = runs["coupled_open"]["k"], runs["coupled_cd"]["k"], runs["coupled_b4c"]["k"]
    say(f"\nEvery configuration is subcritical. Two tanks that alone sit at k ≈ {runs['alone_A']['k'][0]:.3f} "
        f"couple through 3 cm of water to k = {k_open[0]:.4f}; the cadmium sheet is worth "
        f"{(k_open[0]-k_cd[0])*1e5:.0f} pcm and the boron carbide blade {(k_open[0]-k_b4c[0])*1e5:.0f} pcm. "
        "The absorber is a control element in the reactor sense and a GATE terminal in the transistor "
        "sense, and the table is its transfer curve (figure 15 A).\n")
    say("The last two columns are a caution rather than a reassurance. The two tanks are identical and "
        "the absorber sits on their plane of symmetry, so the fission share in B is exactly 0.500 in "
        "the true fundamental mode; the numbers above wander several percent around it while the "
        "Shannon entropy sits flat to a part in a thousand. The entropy is not lying, it is answering a "
        "different question: it sees the shape inside each tank, which has converged, and not the tilt "
        "between them, which has not. Section 3.1 explains why this is a permanent feature of coupled "
        "region gates rather than a shortage of batches, and what it costs. The eigenvalues themselves "
        "survive it, because the tilt mode integrates to zero over the whole system and so cannot "
        "shift a total production rate to first order; the fission matrix does not, which is why it is "
        "measured differently.\n")

    # ---- 3. the fission matrix --------------------------------------------
    say("## 3. The synapse with gain on the diagonal: the fission matrix, checked\n")
    say("K_ij is the number of fission neutrons produced in tank i per fission neutron born in tank j, "
        "the source being the fundamental mode restricted to j and fission treated as capture so that "
        "exactly one generation is counted. This is Avery's coupling coefficient, computed rather than "
        "assumed.\n")
    say("### 3.1 A convergence trap this architecture walks into by construction\n")
    say("Getting that source right was the hardest part of the calculation, and the reason is "
        "structural rather than numerical, so it belongs in the theory and not in a footnote. Two "
        "weakly coupled multiplying regions are the textbook *loosely coupled system*. The "
        "fundamental mode is symmetric between the tanks and the second mode is the tilt from one "
        "tank to the other; their eigenvalues are k_self + k_cross and k_self - k_cross, so the "
        "dominance ratio is\n")
    say("> `DR = (k_self - k_cross)/(k_self + k_cross),`\n")
    say("which approaches one exactly as the coupling is made weak. A gate is *built* to have a small "
        "k_cross. A gate is therefore built to be hard to converge, and the better the gate, the worse "
        "the problem.\n")
    say("| absorber | k_self | k_cross | dominance ratio | generations for a tilt to fall tenfold | tilt in the raw fission bank |")
    say("|---|---|---|---|---|---|")
    for state, desc in STATES:
        K, _ = fission_matrix(runs, state)
        self_, cross = K[0, 0], K[0, 1]
        dr = (self_ - cross) / (self_ + cross)
        bank = runs[f"coupled_{state}"].get("bank_split", {})
        tilt = (bank["B"] / (bank["A"] + bank["B"]) - 0.5) if bank else float("nan")
        say(f"| {desc} | {self_:.4f} | {cross:.4f} | {dr:.4f} | {math.log(10)/-math.log(dr):.0f} | {tilt:+.3f} |")
    say("\nThe tilt then decays by one or two percent per generation while fission bank sampling noise "
        "re excites it just as fast, so the standing tilt of several percent in the last column is not "
        "a transient that more inactive batches remove: it is the equilibrium noise level, and its "
        "correlation length is longer than an affordable active cycle. Worse, the Shannon entropy of "
        "the source is nearly blind to it, because entropy is dominated by the shape inside each tank. "
        "The entropy traces in Section 2 are flat to a part in a thousand while the tilt wanders by "
        "seven percent. An analyst who trusted the entropy would have shipped the wrong matrix, and "
        "the first version of this calculation did exactly that.\n")
    say("### 3.2 The fix: a mirror instead of more batches\n")
    say("The geometry is exactly mirror symmetric in x, so the true fundamental mode puts exactly half "
        "its fissions in each tank. Symmetrising the converged bank, every site with its mirror image, "
        "removes the tilt but not the distortion the tilt leaves in the shape *inside* each tank, and "
        "it was not enough here. What works is to remove the tilt mode from the problem rather than "
        "from the answer: run the half geometry, x > 0 only, with the plane x = 0 reflective. The "
        "antisymmetric mode cannot exist in that model, so there is nothing slow left to converge, and "
        "its fission bank mirrored is the fundamental mode by construction rather than by waiting.\n")
    say("The half model has to earn its place, so it is checked against the full one:\n")
    say("| absorber | half model k (exact symmetric mode) | full model k | difference (pcm) |")
    say("|---|---|---|---|")
    for state, desc in STATES:
        h, f = runs[f"half_{state}"]["k"], runs[f"coupled_{state}"]["k"]
        sig = math.sqrt(h[1] ** 2 + f[1] ** 2) * 1e5
        say(f"| {desc} | {pm(h, 5)} | {pm(f, 5)} | {(h[0]-f[0])*1e5:+.0f} ± {sig:.0f} |")
    say("\nThe two agree, which says the full model's eigenvalues were never the problem: the tilt "
        "integrates to zero over the whole system, so it cannot shift a total production rate, and k "
        "survives it. Only the fission matrix, which asks where the neutrons went and not just how "
        "many, is sensitive to it. Every matrix below is measured from the half model's bank.\n")
    say("Two controls say whether that was necessary. Each runs one generation on a whole source, "
        "exact or raw, and must return k, because one generation of the fundamental mode is the "
        "definition of k.\n")
    say("| absorber | control on the exact mode | control on the raw bank | k | exact error (pcm) | raw error (pcm) |")
    say("|---|---|---|---|---|---|")
    for state, desc in STATES:
        ex = runs[f"coupling_all_{state}"]["global"]["nu-fission"]
        raw = runs[f"coupling_rawall_{state}"]["global"]["nu-fission"]
        k = runs[f"half_{state}"]["k"]
        say(f"| {desc} | {pm(ex, 4)} | {pm(raw, 4)} | {pm(k, 4)} | "
            f"{(ex[0]-k[0])*1e5:+.0f} | {(raw[0]-k[0])*1e5:+.0f} |")
    say("\nThe clearest evidence is not in those columns but in the matrix itself. Measured from the "
        "raw bank, the self multiplication k_self came out as 0.8924, 0.9030, 0.8977 for the three "
        "absorbers: not monotonic, and for cadmium higher than a tank standing alone, which no "
        "absorber placed outside a tank can do. Measured from the exact mode it is "
        f"{fission_matrix(runs, 'open')[0][0,0]:.4f}, {fission_matrix(runs, 'cd')[0][0,0]:.4f}, "
        f"{fission_matrix(runs, 'b4c')[0][0,0]:.4f}: flat, as it must be, because an absorber between "
        "the tanks barely touches what a tank does to its own neutrons. The absorber now changes only "
        "the cross term, which is the gate doing its job and nothing else. A wrong answer that looked "
        "reasonable became a right answer that looks obvious, which is the usual shape of this kind of "
        "error and the reason the control is in the protocol at all.\n")
    say("### 3.3 The matrix, and what its eigenvalue tests\n")
    say("With the source settled, the **dominant eigenvalue of K** tests the two region reduction "
        "itself. It equals k only if each tank's internal shape is the same whether the tank is fed "
        "from inside or through the gap from its neighbour, which is the assumption every coupled "
        "region model makes, this theory's synapse included. Its residual is not an error but a "
        "measurement of how good that assumption is.\n")
    Kmats = {}
    resid = []
    for state, desc in STATES:
        K, S = fission_matrix(runs, state)
        lam, dlam = dominant(K, S)
        k = runs[f"half_{state}"]["k"]
        Kmats[state] = K
        resid.append((lam - k[0]) * 1e5)
        say(f"**{desc[0].upper() + desc[1:]}.**\n")
        say("| | born in A | born in B |")
        say("|---|---|---|")
        say(f"| fission neutrons in A | {K[0,0]:.4f} ± {S[0,0]:.4f} | {K[0,1]:.4f} ± {S[0,1]:.4f} |")
        say(f"| fission neutrons in B | {K[1,0]:.4f} ± {S[1,0]:.4f} | {K[1,1]:.4f} ± {S[1,1]:.4f} |")
        say(f"\n- dominant eigenvalue of K **{lam:.4f} ± {dlam:.4f}** against k **{k[0]:.4f} ± {k[1]:.4f}**, "
            f"a residual of {(lam-k[0])*1e5:+.0f} pcm")
        say("")
    say(f"The eigenvalue of the reduced two by two matrix sits between {min(resid):+.0f} and "
        f"{max(resid):+.0f} pcm of k, the largest belonging to the most weakly coupled case, which is "
        "what one would expect. That residual is the price of describing each tank by a single number: "
        "a neutron arriving from the neighbour enters through one wall and fissions nearer that wall "
        "than a fundamental mode neutron would, so a tank's internal shape is not quite source "
        "independent and no single coupling coefficient can absorb the difference. A third of a "
        "percent is small enough that the synapse picture is sound and large enough that it should be "
        "quoted rather than rounded away. A photon sector network of many weakly coupled cells "
        "inherits both the caveat and, from 3.1, the convergence problem in a sharper form.\n")
    say("**The neutron budget of one fission neutron born in tank A** (the fan out tax of theory "
        "Section 1.3, with real numbers):\n")
    say("| fate | open | cadmium sheet | boron carbide blade |")
    say("|---|---|---|---|")
    rs = [runs[f"coupling_A_{s}"] for s, _ in STATES]
    def absorbed(r, key):
        return r["absorption_by_material"].get(key, [0.0, 0.0])[0]
    rows = [("causes fission neutrons in A (k_AA, self restoring)", [region(r, "A", "nu-fission")[0] for r in rs]),
            ("causes fission neutrons in B (k_BA, the coupling)", [region(r, "B", "nu-fission")[0] for r in rs]),
            ("absorbed in the water", [absorbed(r, "water") for r in rs]),
            ("absorbed in the aluminium", [absorbed(r, "al1100") for r in rs]),
            ("absorbed in the absorber", [absorbed(rs[0], "none"), absorbed(rs[1], "cadmium"), absorbed(rs[2], "b4c")]),
            ("leaks out of the water bath", [1.0 - sum(v[0] for v in r["absorption_by_material"].values()) for r in rs])]
    for lab, vals in rows:
        say(f"| {lab} | " + " | ".join(f"{v:.4f}" for v in vals) + " |")
    kBA = [Kmats[s][1, 0] for s, _ in STATES]
    say(f"\nThe cadmium sheet cuts the coupling k_BA by a factor {kBA[0]/kBA[1]:.1f}, the boron carbide blade "
        f"by {kBA[0]/kBA[2]:.1f}. What reaches the next gate is one or two percent of what was born; the "
        "rest is the price of an isotropic emitter in a moderating body. The 4π loss of theory Section "
        "1.3 is not a metaphor here, it is a row in this table, and the self restoring term k_AA is "
        "the reason the gate has gain at all.\n")

    # ---- 4. the gate ----------------------------------------------------------
    say("## 4. The gate: driven, with multiplication on\n")
    say("A Cf-252 point source (Fröhner Watt spectrum, mean 2.13 MeV) or a 14.1 MeV deuterium tritium "
        "point source on the axis of a tank is the SOURCE terminal. Fixed source transport with full "
        "multiplication gives the steady fission neutron production in each tank per driver neutron; "
        "production in B is the DRAIN current. The point model of coupled regions predicts the same "
        "numbers from Section 3 and the first generation response c of each tank to the driver, "
        "P = (I - K)⁻¹ c, and the comparison is reported because the gap is physics, not noise.\n")
    say("| drive | absorber | c_A | c_B | P_A transport | P_B transport | P_A point model | P_B point model | 1 + P_A + P_B |")
    say("|---|---|---|---|---|---|---|---|---|")
    P = {}
    for state, desc in STATES:
        for drive in ("cfA", "cfB", "dtB"):
            c, cs = vec2(runs[f"firstgen_{drive}_{state}"])
            p, ps = vec2(runs[f"gate_{drive}_{state}"])
            pred = np.linalg.solve(np.eye(2) - Kmats[state], c)
            P[(drive, state)] = (p, ps, pred, c)
            say(f"| {drive} | {desc} | {c[0]:.3f} | {c[1]:.3f} | {p[0]:.2f} ± {ps[0]:.2f} | "
                f"{p[1]:.3f} ± {ps[1]:.3f} | {pred[0]:.2f} | {pred[1]:.3f} | {1+p.sum():.1f} |")
    pa, pa_pred = P[("cfA", "open")][0], P[("cfA", "open")][2]
    Mopen = gain(k_open)[0]
    say(f"\nThe transport drain from A exceeds the point model's, and the source multiplication "
        f"1 + P_A + P_B = {1+pa.sum():.1f} exceeds the eigenvalue gain 1/(1 - k) = {Mopen:.1f}: a point source "
        "on the axis of a tank has more importance than a fundamental mode neutron, so it earns more "
        "than M offspring, and the fission neutrons it makes are clustered at the axis, far from the "
        "other tank, so a smaller share of them cross than the fundamental mode would send. Both "
        "effects are the adjoint flux of theory Section 11 at work, and they are why a gate's gain is a "
        "property of the terminal, not of the medium alone. The fundamental mode arithmetic of Section 3 "
        "is exact for what it describes and undercounts a well placed driver.\n")

    # transistor truth table
    say("### 4.1 The transistor: SOURCE and GATE in, DRAIN out\n")
    say("| driver in A | absorber | drain: fission neutrons born in B per driver neutron | state |")
    say("|---|---|---|---|")
    say("| off | any | 0 | LOW |")
    drains = {s: P[("cfA", s)][0][1] for s, _ in STATES}
    for state, desc in STATES[::-1]:
        say(f"| on | {desc} | {drains[state]:.3f} | {'**HIGH**' if state == 'open' else 'LOW'} |")
    say(f"\nDrain per source neutron with the gate open: **{drains['open']:.2f}**. Every driver neutron "
        f"entering tank A becomes {drains['open']:.1f} fission neutrons born in tank B, on the far side of "
        "an absorber that a coil could move: the output exceeds the input, and the neutron sector gate "
        "has gain with library data and no new physics, as Section 4 of the theory supplement claims. "
        f"ON/OFF contrast: **{drains['open']/drains['cd']:.1f}** against the cadmium sheet and "
        f"**{drains['open']/drains['b4c']:.1f}** against the boron carbide blade. The contrast is modest "
        "and its reason is in the budget above: neutrons cross 3 cm of water still fast or epithermal, "
        "a thermal filter stops only the slow ones, and the fast coupling is a property of the geometry "
        "that no thin absorber touches. A MOSFET's million to one comes from a barrier; this gate has "
        "a filter, and until the coupling path itself is switched (a shutter tank, a longer moderated "
        "gap) that is what its contrast will be.\n")

    # coincidence AND
    say("### 4.2 The coincidence AND: two neutron inputs, one threshold\n")
    say("Both drivers on means the two point sources at equal strength; the run with both sources "
        "present is the superposition check, which fixed source transport obeys exactly.\n")
    say("| absorber | A alone → P_B | B alone → P_B | sum | both drivers, one run | superposition error | strength ratio for a balanced gate | threshold T | margin each side |")
    say("|---|---|---|---|---|---|---|---|---|")
    sup = []
    for state, desc in STATES:
        a = P[("cfA", state)][0][1]; b = P[("cfB", state)][0][1]
        both = vec2(runs[f"gate_cfAB_{state}"])[0][1]
        err = abs(both - (a + b)) / (a + b) * 100
        sup.append(err)
        T = a * math.sqrt(2)
        say(f"| {desc} | {a:.3f} | {b:.3f} | {a+b:.3f} | {both:.3f} | {err:.1f} percent | "
            f"{a/b:.3f} | {T:.3f} | ×{math.sqrt(2):.2f} |")
    say("\nSuperposition holds: two drivers together deliver the sum of what each delivers alone, to "
        f"{max(sup):.1f} percent, which is the counting noise. That is the check that this medium is linear "
        "while its cross sections are frozen, the property theory Section 5.3 asserts and the whole "
        "Green's function reading depends on, measured here in a real geometry rather than in a random "
        "walk toy.\n")
    say("In a linear medium the coincidence AND is a threshold on a weighted sum, a perceptron AND. "
        "The two inputs are unequal, a direct drive against a coupled one, so a balanced gate runs the "
        "second driver at the strength ratio in the table; each input alone then delivers half the "
        "sum, the threshold sits at √2 times one input, and the margin is √2 either side. The weights "
        "are nuclear and programmable (the absorber sets k_BA); the threshold is a comparison of rates "
        "at the boundary, as in the benchtop cell, and stays there until a nonlinear element exists "
        "inside the medium. Section 7 says what the medium offers instead.\n")

    # ---- 5. level restoration ---------------------------------------------
    say("## 5. Level restoration: three inputs, one output\n")
    say("| drive (open) | the input to tank B | mean energy crossing B's wall | fraction of that below 0.625 eV | mean energy of fission neutrons born in B |")
    say("|---|---|---|---|---|")
    spectra = {}
    for drive, desc in (("cfA", "the leakage of tank A, through 3 cm of water"),
                        ("cfB", "a Cf-252 spectrum at the axis, mean 2.13 MeV"),
                        ("dtB", "a 14.1 MeV line at the axis")):
        r = runs[f"gate_{drive}_open"]
        chi, e_chi, _ = spectrum(r, "chi_B", edges)
        cur, e_in, th = spectrum(r, "into_B", edges)
        spectra[drive] = (chi, cur, e_chi, e_in)
        say(f"| {drive} | {desc} | {e_in/1e6:.3f} MeV | {th:.2f} | {e_chi/1e6:.3f} MeV |")
    tv = {d: 0.5 * float(np.sum(np.abs(spectra[d][0] - spectra["cfA"][0]) * np.log(edges[1:] / edges[:-1])))
          for d in ("cfB", "dtB")}
    say(f"\nRead the middle columns with care. When A is driven, everything tank B receives crosses its "
        f"wall, and it arrives moderated: {spectra['cfA'][3]/1e6:.3f} MeV on average, "
        f"{spectrum(runs['gate_cfA_open'], 'into_B', edges)[2]:.0%} of it already thermal, because 3 cm "
        "of water is a moderator as well as a gap. In the other two rows the driver sits inside B, so "
        "the wall current is only the return from the water reflector and the input proper is the "
        "point source itself: a 2 MeV fission spectrum, and a 14.1 MeV line.\n")
    say(f"The three inputs therefore span from thermal to 14 MeV. The fission neutrons born in B differ "
        f"by a total variation distance of {tv['cfB']:.3f} and {tv['dtB']:.3f} between them, which is "
        "counting statistics: one output spectrum, whatever went in, because a fission neutron is born "
        "from the fission barrier and not from whatever triggered it. This is the self restoring class "
        "of theory Section 2, measured (figure 15 C), and it is the property the photon sector cannot "
        "buy at any price, since an isomer cascade emits its own lines and not its trigger's.\n")

    # ---- 6. clock ------------------------------------------------------------
    say("## 6. The clock, the switching time, and the step response\n")
    r = runs["coupled_open"]
    L = r["global"]["inverse-velocity"][0] / r["global"]["nu-fission"][0]
    kpair = k_open[0]
    ts, Pt, Pinf = step_response(Kmats["open"], P[("cfA", "open")][3], L, t_end=12 * L * Mopen)
    pb = Pt[:, 1] / Pinf[1]
    t10, t90 = ts[np.searchsorted(pb, 0.10)], ts[np.searchsorted(pb, 0.90)]
    say(f"- generation time of the pair Λ = **{L*1e6:.1f} µs**; k = {kpair:.4f}; prompt time constant "
        f"Λ/(1 - k) = **{L*Mopen*1e3:.2f} ms**; gain bandwidth product M/τ = 1/Λ = **{1/L/1e3:.1f} kHz**")
    say(f"- step response of the drain (driver in A switched on at t = 0, prompt point kinetics on the "
        f"measured K and Λ): 10 to 90 percent rise in **{(t90-t10)*1e3:.2f} ms** (figure 15 D)")
    beta = region(r, "A", "delayed-nu-fission")[0] / region(r, "A", "nu-fission")[0]
    say(f"- delayed neutrons, ignored above, add a tail on the second scale carrying about "
        f"β k/(1 - k) = {beta*kpair/(1-kpair):.2f} of the prompt step: the theory's remark that precursors "
        "slow the approach as k → 1, quantified\n")
    say("The transistor note's 10 kHz for a thermal assembly is the right order. Ten times the gain "
        "costs ten times the switching time, and the product does not move.\n")

    # ---- 7. feedback ---------------------------------------------------------
    say("## 7. The veto, priced: the only signal controlled inhibition in the neutron sector\n")
    kT, kX = runs["feedback_T350_fixed_density"]["k"], runs["feedback_T350_expanded"]["k"]
    dT = 56.0
    a_dopp, a_exp, a_tot = ((kT[0] - k_open[0]) / dT * 1e5, (kX[0] - kT[0]) / dT * 1e5,
                            (kX[0] - k_open[0]) / dT * 1e5)
    say("| state of the pair, open | k | gain M |")
    say("|---|---|---|")
    say(f"| 294 K | {pm(k_open, 4)} | {pm(gain(k_open), 2)} |")
    say(f"| 350 K, liquid density held | {pm(kT, 4)} | {pm(gain(kT), 2)} |")
    say(f"| 350 K, liquid expanded ({(1-model['water_density_ratio_350K'])*100:.1f} percent less dense) | {pm(kX, 4)} | {pm(gain(kX), 2)} |")
    say(f"\n- temperature coefficient **{a_tot:+.0f} pcm/K** in total: {a_dopp:+.0f} pcm/K from Doppler "
        f"broadening and the thermal scattering law, {a_exp:+.0f} pcm/K from expansion of the liquid")
    say(f"- gain with the pair 56 K hotter: M falls from {gain(k_open)[0]:.2f} to {gain(kX)[0]:.2f}, "
        f"a modulation of {(1-gain(kX)[0]/gain(k_open)[0])*100:.0f} percent")
    dT_half = (1 - k_open[0]) / abs(a_tot / 1e5) if a_tot < 0 else float("inf")
    say(f"- to halve the gain (1 - k doubled) the liquid would have to warm by about **{dT_half:.0f} K**, "
        "which water at atmospheric pressure cannot do\n")
    say("Every coupling in the neutron sector is excitatory: a neutron only ever adds fissions, and an "
        "absorber that burns up disinhibits. The one channel by which a signal lowers another region's "
        "gain is heat, through the density and the Doppler width of the medium, and the table prices "
        "it: sign correct, slow (the thermal time constant of tens of litres of liquid), and worth a "
        "fraction of the gain, not a veto. Signal controlled inversion, which NAND, signed Ising "
        "weights, and Turing completeness all require, is therefore the weak point of the neutron "
        "sector as an embodiment, and the theory supplement now says so in Section 4. The rate coded "
        "machine is untouched: its NOT is a fixed absorber, its AND a coincidence, and neither needs "
        "a signal to invert a signal.\n")

    say("*The gate exists, with gain, with level restoration, with a programmable weight and a clock, "
        "all computed from library data at k below one. What it lacks is a nonlinearity of its own and "
        "an inhibition of its own, and the numbers above say by how much.*")

    open(os.path.join(HERE, "results.md"), "w").write("\n".join(OUT) + "\n")
    print("\n".join(OUT[-10:]))
    print("wrote neutron/results.md")
    figure(curve, runs, P, spectra, edges, ts, Pt, Pinf, L, kpair)


def figure(curve, runs, P, spectra, edges, ts, Pt, Pinf, L, kpair):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    INK, BLUE, RED, GREEN, AMBER, PURPLE, GREY = (
        "#16213e", "#2563eb", "#dc2626", "#16a34a",
        "#d97706", "#7c3aed", "#94a3b8")
    plt.rcParams.update({
        "figure.facecolor": "white", "axes.facecolor": "white",
        "savefig.facecolor": "white", "axes.edgecolor": INK,
        "axes.labelcolor": INK, "text.color": INK, "xtick.color": INK,
        "ytick.color": INK, "axes.titlecolor": INK, "font.size": 11,
        "axes.titlesize": 12, "axes.titleweight": "bold",
        "axes.grid": True, "grid.color": "#e5e7eb", "grid.linewidth": 0.8,
        "axes.spines.top": False, "axes.spines.right": False,
        "figure.dpi": 130, "svg.hashsalt": "nuclear-computer",
    })
    fig, ((A, B), (C, D)) = plt.subplots(2, 2, figsize=(13.2, 9.4))

    # A: the transfer curve of the absorber, with a true gain axis on the right
    cd_pts = [(0, curve[0][1])] + [(int(n.split("cd")[1] or 100), k) for n, k, _ in curve[1:5]]
    x = [p[0] for p in cd_pts]; y = [p[1][0] for p in cd_pts]; e = [p[1][1] for p in cd_pts]
    A.errorbar(x, y, yerr=e, fmt="-o", color=BLUE, lw=2.2, ms=6, capsize=3,
               label="1 mm cadmium sheet")
    kb = curve[5][1]
    A.errorbar([100], [kb[0]], yerr=[kb[1]], fmt="s", color=PURPLE, ms=9, capsize=3,
               label="2 cm boron carbide blade")
    ka = runs["alone_A"]["k"]
    A.axhline(ka[0], color=GREY, ls=":", lw=1.3)
    A.text(50, ka[0] - 0.0009, "one tank alone: no neighbour to couple to",
           color=GREY, fontsize=8, va="top", ha="center")
    lo, hi = min(min(y), kb[0], ka[0]) - 0.004, max(y) + 0.004
    A.set_ylim(lo, hi)
    A.set_xlim(-6, 106)
    A.set_xlabel("absorber inserted between the tanks (percent)")
    A.set_ylabel("k of the pair")
    A.set_title("A.  The GATE terminal: an absorber between the tanks")
    A.legend(frameon=False, fontsize=8.5, loc="upper right")
    # the gain axis is the exact map k -> 1/(1-k), not a rescaled copy
    A2 = A.secondary_yaxis("right", functions=(lambda kk: 1.0 / (1.0 - np.clip(kk, None, 0.9999)),
                                               lambda MM: 1.0 - 1.0 / MM))
    A2.set_ylabel("gain M = 1/(1 − k)", color=AMBER)
    A2.tick_params(colors=AMBER)
    A.annotate(f"k = 1 is {(1-max(y))*1e5:.0f} pcm above the top of this axis:\nevery configuration is subcritical",
               xy=(0.03, 0.06), xycoords="axes fraction", fontsize=8, color=RED)

    # B: the drain, with the gain threshold
    labels = ["boron carbide\nblade in", "cadmium\nsheet in", "open"]
    keys = ["b4c", "cd", "open"]
    vals = [P[("cfA", k)][0][1] for k in keys]
    errs = [P[("cfA", k)][1][1] for k in keys]
    preds = [P[("cfA", k)][2][1] for k in keys]
    B.bar(range(3), vals, yerr=errs, color=[PURPLE, GREY, BLUE], width=0.6, capsize=4,
          label="transport (the drain)", zorder=3)
    B.plot(range(3), preds, "D", color=INK, ms=7, label="point model (I − K)⁻¹c", zorder=4)
    B.axhline(1.0, color=RED, ls="--", lw=1.3, zorder=2)
    B.text(-0.45, 1.03, "unity: one neutron out per neutron in", color=RED, fontsize=8.5,
           ha="left", va="bottom")
    B.set_ylim(0, max(max(vals), max(preds)) * 1.32)
    B.set_xticks(range(3)); B.set_xticklabels(labels, fontsize=9)
    B.set_xlabel("driver in tank A throughout")
    B.set_ylabel("fission neutrons born in B per driver neutron")
    B.set_title("B.  The DRAIN: gain across the gate, and its contrast")
    B.legend(frameon=False, fontsize=8.5, loc="upper left")
    B.annotate("", xy=(2, vals[2]), xytext=(0, vals[0]),
               arrowprops=dict(arrowstyle="<->", color=INK, lw=1.2, shrinkA=2, shrinkB=2))
    B.text(1.0, (vals[0] + vals[2]) / 2 * 1.06, f"ON/OFF contrast {vals[2]/vals[0]:.1f}",
           fontsize=9, ha="center", color=INK, fontweight="bold")

    # C: level restoration. The three outputs coincide, so draw them so that is visible.
    mid = np.sqrt(edges[:-1] * edges[1:])
    styles = [("cfA", BLUE, 5.0, 0.30, "driven from tank A (moderated input)"),
              ("cfB", PURPLE, 2.6, 0.95, "Cf-252 at the axis of B"),
              ("dtB", GREEN, 1.3, 1.00, "14.1 MeV at the axis of B")]
    for drive, c, lw, al, lab in styles:
        C.step(mid, spectra[drive][0], where="mid", color=c, lw=lw, alpha=al,
               label=f"born in B: {lab}", zorder=3)
    arr = spectra["cfA"][1]
    C.step(mid, arr * (spectra["cfA"][0].max() / max(arr.max(), 1e-30)), where="mid",
           color=AMBER, lw=1.6, ls="--", label="input: entering B through its wall (scaled)", zorder=2)
    for e_in, lab, frac, ha in ((2.13e6, "Cf-252 mean input\n2.13 MeV", 0.72, "right"),
                                (14.1e6, "14.1 MeV\ninput line", 0.50, "left")):
        C.axvline(e_in, color=GREY, ls=":", lw=1.2, zorder=1)
        pad = "  " if ha == "left" else ""
        C.text(e_in, spectra["cfA"][0].max() * frac, pad + lab, fontsize=7.6, color=GREY,
               ha=ha, va="center")
    C.set_xscale("log")
    C.set_xlabel("neutron energy (eV)")
    C.set_ylabel("spectrum per unit lethargy (normalised)")
    C.set_title("C.  Level restoration: three inputs, one output")
    C.legend(frameon=False, fontsize=7.8, loc="upper left")
    C.set_xlim(1e-3, 3e7)
    C.set_ylim(0, spectra["cfA"][0].max() * 1.35)
    C.annotate("the three output curves lie on top of one another:\nwhat is emitted does not remember what arrived",
               xy=(0.03, 0.02), xycoords="axes fraction", fontsize=8, color=INK)

    # D: step response
    D.plot(ts * 1e3, Pt[:, 0] / Pinf[0], color=GREY, lw=1.7, label="tank A production")
    D.plot(ts * 1e3, Pt[:, 1] / Pinf[1], color=BLUE, lw=2.4, label="tank B production (the drain)")
    D.axhline(1.0, color=GREY, ls=":", lw=1)
    M = 1 / (1 - kpair)
    D.set_xlabel("time after the driver in A switches on (ms)")
    D.set_ylabel("production, fraction of the steady state")
    D.set_title("D.  Switching: τ = Λ/(1 − k), and M/τ = 1/Λ")
    D.text(0.40, 0.30, f"Λ = {L*1e6:.0f} µs,  k = {kpair:.3f}\nτ = Λ/(1 − k) = {L*M*1e3:.2f} ms\n"
           f"M/τ = 1/Λ = {1/L/1e3:.0f} kHz", transform=D.transAxes, fontsize=9.5, color=INK)
    D.legend(frameon=False, fontsize=8.5, loc="lower right")

    fig.suptitle("Figure 15.  The neutron sector gate, computed from library data at k < 1",
                 fontsize=13, fontweight="bold", y=1.0)
    fig.tight_layout()
    for ext in ("svg", "png"):
        kw = {"metadata": {"Date": None}} if ext == "svg" else {}
        fig.savefig(os.path.join(FIGS, f"fig15_neutron_gate.{ext}"), bbox_inches="tight", **kw)
    plt.close(fig)
    print("wrote fig15_neutron_gate")


if __name__ == "__main__":
    main()
