#!/usr/bin/env python3
# Copyright 2026 Max Freedom Pollard
# SPDX-License-Identifier: Apache-2.0
"""
The ampoule, reported: every derived number, results.md, and figure 17,
from tallies.json and calibration.json. Needs numpy and matplotlib only.

Derived here and nowhere else: the photon budget leaving the core and its
spectrum; the interaction rate, flux and deposited power of every site, the
pile up they imply and the proposal budget they support; the accidental and
true coincidence rates between sites; the boundary count rate and what the
precision law makes of it; the energy budget of the whole vessel; the dose
in air at contact, ten centimetres and a metre from ICRP 116 coefficients;
the transfer curve of the tungsten collar; the Green's function between
sites, its structure, and what the lead septum does to it; and the table
of every number the design notes assumed against the number computed.
"""
import json
import math
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
# an optional directory argument reads and writes there instead (a scratch run)
BASE = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else HERE
FIGS = os.path.join(os.path.dirname(HERE), "figures") if BASE == HERE else BASE
OUT = []
TAU_D = 100e-9        # s, resolving time of a scintillator cell (transistor note: 100 ns)
TAU_W = 100e-9        # s, coincidence window (benchtop cell)
EV = 1.602176634e-19


def say(s=""):
    OUT.append(s)


def pm(m, s, d=3):
    return f"{m:.{d}g} ± {s:.{d}g}"


def si(x, unit="", d=3):
    """A number in engineering notation with a unit; a rate below one per
    second is written as a plain decimal, never with a milli prefix."""
    if x == 0:
        return f"0 {unit}"
    if unit.startswith("/") and abs(x) < 1:
        return f"{x:.2g} {unit}"
    e = int(math.floor(math.log10(abs(x)) / 3) * 3)
    e = max(min(e, 12), -12)
    pre = {-12: "p", -9: "n", -6: "µ", -3: "m", 0: "", 3: "k", 6: "M", 9: "G", 12: "T"}[e]
    return f"{x / 10 ** e:.{d}g} {pre}{unit}"


def times(x):
    """A ratio as a multiplier: 0.033×, 0.33×, 1.05×, 3.1×, 25×."""
    return f"{x:.2g}×" if (x < 0.1 or x >= 10) else f"{x:.2f}×"


SUP = str.maketrans("0123456789-", "⁰¹²³⁴⁵⁶⁷⁸⁹⁻")


def pow10(x):
    """A number to one figure as m×10ⁿ."""
    m, e = f"{x:.0e}".split("e")
    return f"{m}×10{str(int(e)).translate(SUP)}"


def dose_rate(spec, volume, decays, E_edges, dose_E, dose_h):
    """µSv per hour from a flux spectrum tally (particle cm per second, per
    bin, when decays is 1) in a cell of the given volume."""
    mids = np.sqrt(E_edges[:-1] * E_edges[1:])
    h = np.exp(np.interp(np.log(mids), np.log(dose_E), np.log(dose_h)))     # pSv cm2
    flux = np.array(spec) / volume * decays                                   # cm-2 s-1 per bin
    return float((flux * h).sum() * 1e-12 * 3600 * 1e6)


def main():
    doc = json.load(open(os.path.join(BASE, "tallies.json")))
    runs, prov = doc["runs"], doc["provenance"]
    cal = json.load(open(os.path.join(BASE, "calibration.json")))
    D = 1.0                                   # every tally is already per second
    em = runs["emission"]
    E = np.array(prov["energy_edges_eV"]); mids = np.sqrt(E[:-1] * E[1:])
    V = prov["volumes_cm3"]
    src = runs["source"]
    dE, dh = np.array(prov["dose_coefficients_ICRP116_AP"]["energy_eV"]), np.array(prov["dose_coefficients_ICRP116_AP"]["pSv_cm2"])
    geo = prov["geometry_cm"]

    say("# The ampoule in photon transport (regenerated by report.py from tallies.json and calibration.json)\n")
    say(f"OpenMC {prov['openmc_version']}, {prov['library']}, electrons by the {prov['electron_treatment']} "
        f"treatment, budget {prov['budget']} ({prov['wall_clock_minutes']} minutes of wall clock). The core is "
        f"1 GBq each of ⁹⁰Sr and ⁹⁰Y in equilibrium, {prov['decays_per_s']:.0e} decays per second in all; the "
        "sources carry those activities as their strength, so every rate below is a tally per second, with its "
        "Monte Carlo standard deviation.\n")

    # ---- 0. calibration ---------------------------------------------------
    say("## 0. Calibration: the photon instrument against references that are not OpenMC\n")
    say("| material | energy (keV) | μ/ρ from the library (cm²/g) | NIST XCOM | ratio |")
    say("|---|---|---|---|---|")
    worst_att = 0.0
    for r in cal["attenuation"]:
        worst_att = max(worst_att, abs(r["ratio"] - 1))
        say(f"| {r['material']} | {r['E_keV']:.0f} | {r['library']:.4f} | {r['xcom']:.4f} | {r['ratio']:.3f} |")
    say(f"\nThe library's total attenuation agrees with XCOM to {worst_att*100:.1f} percent at worst across "
        "lead, iron, tungsten and water from 100 keV to 2 MeV: the data.\n")
    say("| slab | energy (keV) | uncollided fraction, Monte Carlo | exp(−μx) | ratio |")
    say("|---|---|---|---|---|")
    worst_tr = 0.0
    for r in cal["transmission"]:
        worst_tr = max(worst_tr, abs(r["ratio"] - 1))
        say(f"| {r['thickness_cm']:g} cm {r['material']} | {r['E_keV']:.0f} | {r['mc']:.4f} ± {r['mc_std']:.4f} | {r['expected']:.4f} | {r['ratio']:.3f} |")
    say(f"\nUncollided transmission through slabs of up to three mean free paths reproduces the exponential to "
        f"{worst_tr*100:.1f} percent at worst: the transport.\n")
    say("| target | electron energy (keV) | photons escaping per electron | energy radiated, fraction of T | thick target rule | ratio |")
    say("|---|---|---|---|---|---|")
    for r in cal["bremsstrahlung"]:
        say(f"| {r['material']} | {r['T_keV']:.0f} | {r['photons_per_electron']:.3f} | {r['radiated_fraction']:.4f} | {r['rule']:.4f} | {r['ratio']:.2f} |")
    say("\nThe energy an electron radiates as it stops, measured as what escapes a sphere thin enough to "
        "absorb little of it, lands within the few tens of percent that the thick target rule "
        "6×10⁻⁴ Z T is good for. OpenMC's thick target bremsstrahlung treatment was validated by its authors "
        "against ESTAR and Geant4 (Lund and Romano, 2018); this only shows that the version and data in "
        "hand behave as published. It is the source term of everything below, and it is the least certain "
        "link in the chain: the numbers that descend from it should be read to about ten percent.\n")

    # ---- 1. the source ----------------------------------------------------
    say("## 1. The source: what the core actually emits\n")
    cur = np.array(src["core_out"]["mean"]); cur_s = np.array(src["core_out"]["std"])
    n_out = cur.sum() * D
    e_mean = (cur * mids).sum() / cur.sum()
    f100 = cur[mids > 1e5].sum() / cur.sum(); f500 = cur[mids > 5e5].sum() / cur.sum()
    heat = src["heating_by_cell"]
    groups = {"core (pellet and capsule)": ["pellet", "capsule"], "lamp cell (krypton and wall)": ["krypton", "lamp_wall", "inner_air"],
              "collar": ["collar"], "compute shell (glass and sites)": ["glass"] + [k for k in heat if k.startswith("site_")] + [k for k in heat if k.startswith("opening_")],
              "trim ring": ["trim_air"], "boundary (paddles, CZT, silicon)": ["paddles", "sipm_si"] + [k for k in heat if k.startswith("czt_")],
              "shield (PMMA, lead, titanium)": ["pmma", "lead", "titanium"], "outside": ["contact", "dose10", "dose100", "air"]}
    power = {g: sum(heat[k][0] for k in ks if k in heat) * EV for g, ks in groups.items()}
    power["core (pellet and capsule)"] += em["electron_heating_W"]          # the betas themselves, from the emission stage
    total_power = sum(power.values())
    emitted = np.array(em["spectrum_per_s"]); e_emit = (emitted * mids).sum() / emitted.sum()
    say(f"- bremsstrahlung made in the pellet ceramic: {si(emitted.sum(), '/s')}, "
        f"{emitted.sum()/prov['decays_per_s']:.4f} photons per decay at a mean energy of {e_emit/1e3:.0f} keV; "
        f"the betas deposit {si(em['electron_heating_W'], 'W')} there")
    say(f"- photons leaving the source capsule into the lamp cell: **{si(n_out, '/s')}** "
        f"(± {math.sqrt((cur_s**2).sum())/cur.sum():.1%}), {n_out/emitted.sum():.0%} of those made, mean energy "
        f"**{e_mean/1e3:.0f} keV**, {f100:.0%} above 100 keV and {f500:.1%} above 500 keV: the pellet and its "
        "capsule absorb the soft end of their own light")
    say(f"- power deposited in the whole vessel: **{si(total_power, 'W')}** against the design note's 181 µW for "
        "1 GBq of ⁹⁰Sr/⁹⁰Y (SEALED.md ledger), the difference being the beta spectra used and the photons that escape")
    say("")
    say("| where the energy goes | power |")
    say("|---|---|")
    for g, p in power.items():
        say(f"| {g} | {si(p, 'W')} |")
    say("")
    say("Almost all of the decay energy stops in the pellet and its capsule, as the design intends: it is "
        "the lamp's heat and the betavoltaic's supply. What leaves as photons is the bremsstrahlung of a "
        f"thick target, {emitted.sum()*e_emit*EV/total_power:.1%} of the power, and that is the whole budget the "
        "compute shell, the boundary and the shield have to work with.\n")

    # ---- 2. the compute shell --------------------------------------------
    say("## 2. The compute shell: what each site sees\n")
    tot = np.array(src["sites"]["total"][0]) * D; tot_s = np.array(src["sites"]["total"][1]) * D
    flux = np.array(src["sites"]["flux"][0]) / V["site"] * D
    ph = np.array(src["sites"]["heating"][0]) * D * EV
    r_mean, r_min, r_max = tot.mean(), tot.min(), tot.max()
    pile = r_mean * TAU_D
    say(f"- interaction rate per site: mean **{si(r_mean, '/s')}**, from {si(r_min, '/s')} to {si(r_max, '/s')} "
        f"(the lattice is symmetric, so the spread is the height dependence and statistics); "
        f"photon flux {si(flux.mean(), '/cm²/s')}; deposited {si(ph.mean(), 'W')} per site")
    say(f"- all 64 sites together: **{si(tot.sum(), '/s')}** interactions, against the design note's proposal "
        f"budget of 10⁶ per second (SEALED.md Section 8): the shell is fed {times(tot.sum()/1e6)} what the sampler was priced at")
    say(f"- pile up: the mean site interacts {pile:.2g} times per {TAU_D*1e9:.0f} ns resolving time, so "
        f"{(1-math.exp(-pile))*100:.2g} percent of its events overlap another; the theory's floor plan n ≳ λτ_d asks for "
        f"{tot.sum()*TAU_D:.2g} sites at this activity, and there are 64")
    acc = 2 * TAU_W * r_mean ** 2
    say(f"- accidental coincidences between two mean sites in a {TAU_W*1e9:.0f} ns window: 2τ r² = "
        f"**{si(acc, '/s')}**, the raw material of the coincidence multiplier; the precision law "
        f"then gives {acc/2**8:.2g} four bit readings of it per second and {acc/2**16:.2g} eight bit ones")
    csi = runs.get("source_csi")
    if csi:
        tot_c = np.array(csi["sites"]["total"][0]) * D
        pile_c = tot_c.mean() * TAU_D; acc_c = 2 * TAU_W * tot_c.mean() ** 2
        csi_ratio = tot_c.sum() / tot.sum()
        say(f"- **the same shell with CsI cells**, the build note's other option: mean **{si(tot_c.mean(), '/s')}** per site, "
            f"**{si(tot_c.sum(), '/s')}** over all 64, {times(csi_ratio)} the plastic figure and {times(tot_c.sum()/1e6)} the "
            f"proposal budget; pile up {pile_c:.2g} per resolving time ({(1-math.exp(-pile_c))*100:.2g} percent of events overlap, "
            f"{tot_c.sum()*TAU_D:.2g} sites needed); accidental coincidences between two mean sites {si(acc_c, '/s')}, "
            f"{acc_c/2**8:.2g} four bit and {acc_c/2**16:.2g} eight bit readings per second")
    say("")
    spec = np.array(src["site_spectrum"]); spec = spec / spec.sum()
    e_site = (spec * mids).sum()
    say(f"The field in a site has mean energy {e_site/1e3:.0f} keV, and {spec[mids < 1e5].sum():.0%} of it is below "
        "100 keV: what reaches the shell is already the soft end of the bremsstrahlung, filtered by the "
        "capsule, the lamp wall and the collar. "
        + (f"Which cell material the builder chooses decides whether the sampler is fed at all: 2 mm of plastic is a "
           f"Compton scatterer that a {e_site/1e3:.0f} keV field crosses almost untouched, and 2 mm of CsI, with the "
           f"photoelectric effect of iodine and caesium and four times the density, interacts {times(csi_ratio)} as often. "
           f"The note offered either; the transport says CsI, and "
           + ("that with CsI the shell meets the proposal budget" if tot_c.sum() >= 1e6 else
              f"that even with CsI the shell is {times(1e6/tot_c.sum())} short of the proposal budget")
           + ". The rest of this report runs the vessel with plastic cells, the conservative choice; the collar's "
           "contrast is given for both, and the septum's factor, a ratio of couplings through the same lead, is "
           "given for plastic." if csi else "") + "\n")

    # ---- 3. the gate --------------------------------------------------------
    say("## 3. The GATE: the tungsten collar's transfer curve\n")
    say("Every site faces the lamp cell through an opening in a 2 mm tungsten sleeve; the opening's width "
        "is the site's thinning aperture, the mechanical GATE terminal of the reference transistor. The "
        "collar was run at five widths.\n")
    say("| opening (percent of nominal) | mean site rate | relative to open |")
    say("|---|---|---|")
    curve = []
    for f, name in ((0.0, "gate_000"), (0.25, "gate_025"), (0.5, "gate_050"), (0.75, "gate_075"), (1.0, "source")):
        r = runs[name]
        m = np.array(r["sites"]["total"][0]).mean() * D
        s = np.sqrt((np.array(r["sites"]["total"][1]) ** 2).sum()) / 64 * D       # standard error of the mean over the 64 sites
        curve.append((f, m, s))
    for f, m, s in curve:
        say(f"| {f*100:.0f} | {si(m, '/s')} ± {si(s, '/s', 2)} | {m/curve[-1][1]:.3f} |")
    contrast = curve[-1][1] / curve[0][1]
    contrast_s = contrast * math.sqrt((curve[-1][2] / curve[-1][1]) ** 2 + (curve[0][2] / curve[0][1]) ** 2)
    g0c = runs.get("gate_000_csi")
    if csi and g0c:
        m0c = np.array(g0c["sites"]["total"][0]).mean() * D
        s0c = np.sqrt((np.array(g0c["sites"]["total"][1]) ** 2).sum()) / 64 * D
        s1c = np.sqrt((np.array(csi["sites"]["total"][1]) ** 2).sum()) / 64 * D
        contrast_c = tot_c.mean() / m0c
        contrast_cs = contrast_c * math.sqrt((s1c / tot_c.mean()) ** 2 + (s0c / m0c) ** 2)
        csi_line = (f" With CsI cells, which the soft end of the spectrum reaches and the closed collar removes, the "
                    f"contrast is **{contrast_c:.2f}** (± {contrast_cs:.2f}): {si(m0c, '/s')} closed against {si(tot_c.mean(), '/s')} open.")
    else:
        csi_line = ""
    say(f"\nON/OFF contrast of the collar: **{contrast:.2f}** (± {contrast_s:.2f}) with plastic cells.{csi_line} The closed state is not dark, because 2 mm of "
        "tungsten stops the soft bremsstrahlung and passes the hard tail (a 1 MeV photon has a 30 percent "
        "chance of crossing it uncollided), and because photons scattered in the glass reach the sites "
        "from the side. The aperture is an analog knob over a modest range, which is what the neutron "
        "sector's absorber turned out to be too, and for the same reason: an absorber in a path is a "
        "filter, not a barrier, unless it is thick enough to stop the whole spectrum.\n")

    # ---- 4. the synapse ---------------------------------------------------
    say("## 4. The synapse: the Green's function between sites\n")
    say("A photon born in site j (isotropically, with the spectrum the source stage found in the sites) "
        "interacts in site k with probability G_kj. This is the weight matrix of the theory's transport "
        "synapse for the real geometry, the object Open Problem 4 asked for, measured 64 × 64.\n")
    G = np.array(runs["synapse_open"]["G"]); Gs = np.array(runs["synapse_open"]["std"])
    N_AZ, N_Z = 8, 8
    diag = np.mean([G[j, j] for j in range(64)])
    az_nb, z_nb, dg_nb, far = [], [], [], []
    for j in range(64):
        iz, ia = divmod(j, N_AZ)
        for k in range(64):
            if k == j:
                continue
            kz, ka = divmod(k, N_AZ)
            da = min(abs(ka - ia), N_AZ - abs(ka - ia)); dz = abs(kz - iz)
            if da == 1 and dz == 0:
                az_nb.append(G[k, j])
            elif da == 0 and dz == 1:
                z_nb.append(G[k, j])
            elif da == 1 and dz == 1:
                dg_nb.append(G[k, j])
            else:
                far.append(G[k, j])
    fan = np.array([G[:, j].sum() - G[j, j] for j in range(64)])
    say("| coupling | mean G_kj (interactions in k per photon born in j) |")
    say("|---|---|")
    say(f"| a site with itself (G_jj) | {diag:.2e} |")
    say(f"| nearest neighbour around the ring (Δθ = 45°) | {np.mean(az_nb):.2e} |")
    say(f"| nearest neighbour along the axis (Δz = 1 cm) | {np.mean(z_nb):.2e} |")
    say(f"| diagonal neighbour | {np.mean(dg_nb):.2e} |")
    say(f"| everything farther | {np.mean(far):.2e} (mean), {np.max(far):.2e} (largest) |")
    say(f"| all other sites together, per photon born | {fan.mean():.2e} |")
    say("")
    say(f"A photon born in a 2 mm site has a {diag:.1%} chance of interacting in it and a {fan.mean():.1%} chance of "
        "interacting in any of the other 63; the rest is lost to the glass, the collar, the boundary and the "
        "shield. That is the fan out tax of theory Section 1.3 for this geometry: the weights of the "
        f"synapse are of order {pow10(np.mean(az_nb))}, and a signal handed from a site to its nearest neighbour "
        f"is attenuated by {pow10(1/np.mean(az_nb))} at every hop. The compiler's toy fabric (transport/compiler_demo.py) "
        f"had weights of order a tenth; the real shell is {math.log10(0.1/np.mean(az_nb)):.0f} orders down, which the sampler's rate "
        "coding absorbs as budget rather than as error (theory Section 10.1), but which sets what a "
        "gigabecquerel actually buys. These are plastic cells; CsI cells would raise every entry, the self "
        "term and the couplings alike, by roughly the material ratio of Section 2, and the fan out fraction with them.\n")
    Gsep = np.array(runs["synapse_septum"]["G"])
    srcs = runs["synapse_septum"]["sources"]
    blocked, control = [], []
    for j in srcs:
        iz, ia = divmod(j, N_AZ)
        if ia != 0:
            continue
        for kz in range(N_Z):
            k1 = kz * N_AZ + 1; k7 = kz * N_AZ + 7
            if G[k1, j] > 0:
                blocked.append(Gsep[k1, j] / G[k1, j])
            if G[k7, j] > 0:
                control.append(Gsep[k7, j] / G[k7, j])
    say(f"**The septum.** A 1 mm lead sheet between sector 0 and sector 1 leaves sector 0's coupling to sector 1 "
        f"at {np.mean(blocked):.2f} of its open value and its coupling to sector 7, on the unshielded side, at "
        f"{np.mean(control):.2f}: the inhibitory septum of the build note blocks the soft part of the coupling "
        "and passes the hard part, a factor rather than a wall, like the collar and like the cadmium sheet of "
        "the neutron gate. Fixed absorbers program weights in this machine; they do not cut wires.\n")

    # ---- 5. the boundary -----------------------------------------------------
    say("## 5. The boundary: what the mouth actually counts\n")
    det = src["detectors"]
    names = det["names"]
    rates = np.array(det["total"][0]) * D; rs = np.array(det["total"][1]) * D
    paddle, czt = rates[0], rates[1:].sum()
    say("| detector | interaction rate | deposited power |")
    say("|---|---|---|")
    heats = np.array(det["heating"][0]) * D * EV
    say(f"| scintillator paddles and caps (24 SiPM tiles) | {si(paddle, '/s')} ± {si(rs[0], '/s', 2)} | {si(heats[0], 'W')} |")
    say(f"| four CZT pixels together | {si(czt, '/s')} | {si(heats[1:].sum(), 'W')} |")
    say("")
    total_det = paddle + czt
    say(f"- detected boundary events: **{si(total_det, '/s')}**, against the design note's budget of 10⁷ per second "
        f"(SEALED.md Section 7): **{times(total_det/1e7)}** the assumption; the fraction of photons leaving the core that "
        f"interact in the boundary is {total_det/n_out:.0%}")
    say(f"- by the precision law, that budget supports {total_det/2**16:.0f} eight bit reads per second, "
        f"{total_det/2**12:.0f} at six bits and {total_det/2**8:.0f} at four; the note priced 153, 2,441 and 39,062")
    ds = np.array(src["detector_spectrum"]["paddles"]); ds = ds / max(ds.sum(), 1e-30)
    say(f"- the paddle spectrum has mean energy {(ds*mids).sum()/1e3:.0f} keV; a 6 mm plastic paddle is a Compton "
        "scatterer, not a photopeak detector, and the CZT pixels are where the energy division channels of "
        "gates/edm_channels.md would be read\n")

    # ---- 6. dose ----------------------------------------------------------------
    say("## 6. The dose outside: the health physics the build note deferred\n")
    dc = dose_rate(src["contact"]["mean"], V["contact"], D, E, dE, dh)
    d10 = dose_rate(src["dose10"]["mean"], V["dose10"], D, E, dE, dh)
    d100 = dose_rate(src["dose100"]["mean"], V["dose100"], D, E, dE, dh)
    leak = np.array(src["leak"]["mean"]); n_leak = leak.sum() * D
    say("| where | ambient dose rate (ICRP 116, anterior posterior, photons) |")
    say("|---|---|")
    say(f"| at the titanium wall | **{dc:.3g} µSv/h** |")
    say(f"| 10 cm from the centre | {d10:.3g} µSv/h |")
    say(f"| 1 m from the centre | **{d100:.3g} µSv/h** |")
    say("")
    say(f"- photons escaping the shield: {si(n_leak, '/s')}, {n_leak/n_out:.1%} of what left the core, with mean energy "
        f"{(leak*mids).sum()/max(leak.sum(),1e-30)/1e3:.0f} keV: the hard tail again")
    say(f"- for scale, the public dose limit of 1 mSv per year is 0.11 µSv/h continuously; at 1 m this vessel "
        f"{'stays under it' if d100 < 0.11 else f'exceeds it by {d100/0.11:.0f}×'}, and at the wall it "
        f"{'is under it' if dc < 0.11 else f'is {dc/0.11:.0f}× over'}. The build note said the shield was sized "
        "with margin and that the final figure was the builder's to certify; this is that figure, for the "
        "photons, from the same library that licenses shielding")
    say("- the bremsstrahlung of ⁹⁰Sr/⁹⁰Y is a known shielding problem precisely because it is hard: the "
        "design's 4 mm of lead is a filter for it, not a wall, and a laboratory instrument at a gigabecquerel "
        "would sit in a lead pot. Nothing in the computation contradicts the note's licence class, "
        "institutional; it puts a number on why\n")

    # ---- 7. verdict ------------------------------------------------------------
    say("## 7. The design notes, checked\n")
    say("| what the notes assumed | where | computed here |")
    say("|---|---|---|")
    say(f"| deposited power, 181 µW per GBq | SEALED.md ledger | {si(total_power, 'W')} for the pair |")
    say(f"| boundary budget 10⁷ detected events per second | SEALED.md Section 7 | {si(total_det, '/s')} |")
    say(f"| percent level boundary collection | SEALED.md Section 7 | {total_det/n_out:.0%} of core photons |")
    say(f"| proposal budget 10⁶ per second across 64 sites | SEALED.md Section 8 | {si(tot.sum(), '/s')} with plastic cells"
        + (f", {si(tot_c.sum(), '/s')} with CsI" if csi else "") + " |")
    say(f"| cells of plastic scintillator or CsI | EMBODIMENT.md Section 1.2 | "
        + (f"CsI, by {times(csi_ratio)} in rate" if csi else "plastic only was run") + " |")
    say(f"| pile up ceiling, sites ≳ λ τ_d | THEORY.md Section 3.2 | {tot.sum()*TAU_D:.2g} sites needed with plastic"
        + (f", {tot_c.sum()*TAU_D:.2g} with CsI" if csi else "") + ", 64 present |")
    say(f"| the aperture as the GATE terminal | transistor/README.md | contrast {contrast:.2f} through 2 mm of tungsten"
        + (f" with plastic cells, {contrast_c:.2f} with CsI" if csi_line else "") + " |")
    say(f"| lead septa as inhibitory blocking | EMBODIMENT.md Section 1.2 | coupling reduced to {np.mean(blocked):.2f}, not cut |")
    say(f"| weights written by geometry | README, the scattering gate | nearest neighbour G ≈ {pow10(np.mean(az_nb))}, fan out {fan.mean():.1%} |")
    say(f"| shield sized with margin, dose to be certified | EMBODIMENT.md Section 1.5 | {dc:.3g} µSv/h at the wall, {d100:.3g} µSv/h at 1 m |")
    say("")
    b_ratio = total_det / 1e7
    boundary_verdict = (f"closes at the boundary with {times(b_ratio)} the assumed count" if b_ratio >= 1 else
                        f"falls short at the boundary by {times(1/b_ratio)}" if b_ratio >= 0.1 else
                        f"fails at the boundary by an order of magnitude, {times(1/b_ratio)}")
    if csi:
        site_verdict = (f"reaches its proposal budget in the sites only with CsI cells ({times(tot_c.sum()/1e6)} the budget, "
                        f"against {times(tot.sum()/1e6)} with plastic)" if tot_c.sum() >= 1e6 else
                        f"misses its proposal budget in the sites with either cell material ({times(tot.sum()/1e6)} with plastic, "
                        f"{times(tot_c.sum()/1e6)} with CsI)")
    else:
        site_verdict = f"is fed {times(tot.sum()/1e6)} its proposal budget in the sites"
    say(f"*The ampoule's budget {boundary_verdict} and {site_verdict}; its wall is thinner than its own spectrum; "
        "and its two mechanical controls, the aperture and the septum, are knobs rather than switches for the same "
        "reason the neutron gate's absorber was. The machine the theory can seal today is a rate coded sampler "
        "whose weights are small and whose photons are hard, and every one of those adjectives is now a number.*")

    open(os.path.join(BASE, "results.md"), "w").write("\n".join(OUT) + "\n")
    print("\n".join(OUT[-6:]))
    print("wrote ampoule/results.md")
    figure(cur, mids, D, curve, G, Gsep, srcs, power, dc, d10, d100, ds, leak, spec,
           (tot_c.mean(), np.sqrt((np.array(csi["sites"]["total"][1]) ** 2).sum()) / 64 * D) if csi else None)


def figure(cur, mids, D, curve, G, Gsep, srcs, power, dc, d10, d100, ds, leak, spec, csi_point=None):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.colors import LogNorm
    INK, BLUE, RED, GREEN, AMBER, PURPLE, GREY = (
        "#16213e", "#2563eb", "#dc2626", "#16a34a", "#d97706", "#7c3aed", "#94a3b8")
    plt.rcParams.update({
        "figure.facecolor": "white", "axes.facecolor": "white", "savefig.facecolor": "white",
        "axes.edgecolor": INK, "axes.labelcolor": INK, "text.color": INK, "xtick.color": INK,
        "ytick.color": INK, "axes.titlecolor": INK, "font.size": 11, "axes.titlesize": 12,
        "axes.titleweight": "bold", "axes.grid": True, "grid.color": "#e5e7eb",
        "grid.linewidth": 0.8, "axes.spines.top": False, "axes.spines.right": False,
        "figure.dpi": 130, "svg.hashsalt": "nuclear-computer"})
    fig, ((A, B), (C, Dax)) = plt.subplots(2, 2, figsize=(13.4, 9.6))

    # A: spectra per second per keV
    def per_keV(y):
        edges = np.sqrt(mids[:-1] * mids[1:])
        w = np.diff(np.concatenate([[mids[0] ** 2 / edges[0]], edges, [mids[-1] ** 2 / edges[-1]]])) / 1e3
        return np.array(y) * D / np.maximum(w, 1e-30)
    A.plot(mids / 1e3, per_keV(cur), color=BLUE, lw=2.0, label="leaving the source capsule")
    A.plot(mids / 1e3, per_keV(spec * cur.sum()), color=AMBER, lw=1.6, ls="--", label="in a site (shape, scaled)")
    A.plot(mids / 1e3, per_keV(leak), color=RED, lw=1.8, label="escaping the shield")
    A.axvline(2280, color=GREY, ls=":", lw=1.2)
    A.set_xscale("log"); A.set_yscale("log")
    A.text(2150, A.get_ylim()[1] * 0.5, "⁹⁰Y endpoint", color=GREY, fontsize=8, ha="right", va="top")
    A.set_xlim(10, 3000); A.set_xlabel("photon energy (keV)"); A.set_ylabel("photons per second per keV")
    A.set_title("A.  The bremsstrahlung of 1 GBq of ⁹⁰Sr/⁹⁰Y, and what gets out")
    A.legend(frameon=False, fontsize=8.5, loc="lower left")

    # B: the collar transfer curve
    x = [f * 100 for f, _, _ in curve]; y = [m for _, m, _ in curve]; e = [s for _, _, s in curve]
    B.errorbar(x, y, yerr=e, fmt="-o", color=BLUE, lw=2.2, ms=6, capsize=3, label="mean site interaction rate, plastic cells")
    if csi_point:
        B.errorbar([100], [csi_point[0]], yerr=[csi_point[1]], fmt="D", color=AMBER, ms=7, capsize=3, label="CsI cells, collar open")
    B.axhline(1 / TAU_D, color=RED, ls="--", lw=1.3); B.text(2, 1 / TAU_D * 1.15, "pile up ceiling, 1/τ_d", color=RED, fontsize=8.5)
    B.axhline(1e6 / 64, color=AMBER, ls=":", lw=1.3); B.text(2, 1e6 / 64 * 1.15, "design proposal budget per site", color=AMBER, fontsize=8.5)
    B.set_yscale("log"); B.set_ylim(min(y) / 3, 3e7); B.set_xlim(-5, 108)
    B.set_xlabel("collar opening (percent of nominal)"); B.set_ylabel("interactions per second per site")
    B.set_title("B.  The GATE terminal: the tungsten collar's transfer curve")
    B.legend(frameon=False, fontsize=8.5, loc="lower right")

    # C: the Green's function
    Gp = np.maximum(G, 1e-6)
    im = C.imshow(Gp, norm=LogNorm(vmin=1e-5, vmax=max(Gp.max(), 1e-2)), cmap="Blues", origin="lower")
    for b in range(8, 64, 8):
        C.axhline(b - 0.5, color=GREY, lw=0.5); C.axvline(b - 0.5, color=GREY, lw=0.5)
    C.set_xlabel("photon born in site j (8 heights × 8 azimuths)"); C.set_ylabel("interacts in site k")
    C.set_title("C.  The synapse: G between the 64 sites")
    C.grid(False)
    plt.colorbar(im, ax=C, fraction=0.046, pad=0.03, label="G_kj per photon")

    # D: energy budget and dose
    labels = list(power); vals = [power[k] * 1e6 for k in labels]
    Dax.barh(range(len(labels)), vals, color=[GREY, AMBER, INK, BLUE, GREY, GREEN, PURPLE, RED], height=0.6)
    Dax.set_yticks(range(len(labels))); Dax.set_yticklabels([l.split(" (")[0] for l in labels], fontsize=8.5)
    Dax.set_xscale("log"); Dax.set_xlabel("deposited power (µW)")
    Dax.set_title("D.  Where the energy goes, and the dose outside")
    Dax.text(0.98, 0.96, f"ambient dose rate\nat the wall: {dc:.3g} µSv/h\nat 10 cm: {d10:.3g} µSv/h\nat 1 m: {d100:.3g} µSv/h",
             transform=Dax.transAxes, fontsize=9, ha="right", va="top", color=INK,
             bbox=dict(boxstyle="round", fc="white", ec=GREY))

    fig.suptitle("Figure 17.  The ampoule in real photon transport", fontsize=13, fontweight="bold", y=1.0)
    fig.tight_layout()
    for ext in ("svg", "png"):
        kw = {"metadata": {"Date": None}} if ext == "svg" else {}
        fig.savefig(os.path.join(FIGS, f"fig17_ampoule.{ext}"), bbox_inches="tight", **kw)
    plt.close(fig)
    print("wrote fig17_ampoule")


if __name__ == "__main__":
    main()
