#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
The compiler, demonstrated three ways (theory Section 11).

A computer needs a compiler: an algorithm from the problem (a target
weight matrix G*) to the hardware (a material layout). This script
implements and verifies all three compilation routes on one exact,
discretized transport model:

  A. Full custom: adjoint gradient descent over per cell survival
     (absorber) densities. The Jacobian of the whole port to port
     matrix with respect to every cell comes from two transport solves
     (forward flux times adjoint importance), verified here against
     finite differences at machine precision.
  B. Crossbar: a universal collimated fabric where weights are aperture
     transmissions; compilation is elementwise division, exact, no
     optimization.
  C. Self calibration: SPSA (Spall 1992) driving the same layout using
     only Poisson noisy measurements of G, two measurements per step
     regardless of parameter count: compilation through a sealed wall.

Model: photons enter at 4 input ports, random walk with forward bias
through a 12 x 12 cell medium with per cell survival s in [0.95, 0.9995] (mostly transparent, selectively absorbing, as a real weight plate is),
and exit at 4 output ports. G(s) is computed exactly by the absorbing
Markov chain fundamental matrix, so every claim below is linear algebra,
not sampling. Outputs: compiler_results.md, figures/fig14_compiler.*
"""
import math
import os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
FIGS = os.path.join(os.path.dirname(HERE), "figures")
RNG = np.random.default_rng(93)           # seed honors Mo-93

NX, NY = 12, 12
V = NX * NY
N_IN, N_OUT = 4, 4
S_MIN, S_MAX = 0.95, 0.9995

OUT = []


def say(s=""):
    OUT.append(s)
    print(s)


# ---------------------------------------------------------------------------
# the transport fabric: movement matrix M (cell to cell) and exits X (cell
# to port), fixed by geometry; survival s_v is the compiled variable
# ---------------------------------------------------------------------------
def build_fabric():
    def idx(x, y):
        return y * NX + x
    M = np.zeros((V, V))
    X = np.zeros((V, N_OUT))
    p_r, p_u, p_d, p_l = 0.38, 0.24, 0.24, 0.14
    out_rows = np.linspace(1, NY - 2, N_OUT).astype(int)
    for y in range(NY):
        for x in range(NX):
            v = idx(x, y)
            moves = [(x + 1, y, p_r), (x, y + 1, p_u),
                     (x, y - 1, p_d), (x - 1, y, p_l)]
            for xx, yy, p in moves:
                if xx < 0:
                    M[v, v] += p                      # reflect at entry wall
                elif xx >= NX:
                    d = np.abs(out_rows - y)
                    o = int(np.argmin(d))
                    if d[o] <= 1:
                        X[v, o] += p                  # exit to nearest port
                    # else lost at the wall (leakage)
                elif yy < 0 or yy >= NY:
                    pass                              # lost top/bottom
                else:
                    M[v, idx(xx, yy)] += p
    in_rows = np.linspace(1, NY - 2, N_IN).astype(int)
    B = np.zeros((N_IN, V))
    for i, y in enumerate(in_rows):
        B[i, idx(0, y)] = 1.0
    return M, X, B


M, X, B = build_fabric()


def transport(s):
    """Exact G, forward visit densities phi, and importances psi."""
    Q = s[:, None] * M                                # survive at u, move
    Ninv = np.linalg.inv(np.eye(V) - Q)
    phi = B @ Ninv                                    # (N_IN, V) visits
    c = s[:, None] * X                                # exit vectors
    G = phi @ c                                       # (N_IN, N_OUT)
    psi = M @ (Ninv @ c) + X                          # (V, N_OUT) importance
    return G, phi, psi


def jacobian_entry(phi, psi, i, o):
    """d G[i,o] / d s_v = phi_i(v) * psi_o(v): flux times importance."""
    return phi[i] * psi[:, o]


def loss_and_grad(s, G_star, zero_mask, mu=4.0):
    G, phi, psi = transport(s)
    R = G - G_star
    R2 = mu * (G * zero_mask)
    L = 0.5 * np.sum(R * R) + 0.5 * np.sum(R2 * (G * zero_mask))
    grad = np.zeros(V)
    W = R + mu * (G * zero_mask)
    for i in range(N_IN):
        for o in range(N_OUT):
            grad += W[i, o] * jacobian_entry(phi, psi, i, o)
    return L, grad, G


def main():
    say("# Compiler results (regenerated by compiler_demo.py)\n")

    # ---- verify the adjoint formula against finite differences -----------
    s0 = RNG.uniform(0.96, 0.999, V)
    G0, phi0, psi0 = transport(s0)
    adj = jacobian_entry(phi0, psi0, 1, 2)
    h = 1e-6
    fd = np.zeros(5)
    cells = RNG.choice(V, 5, replace=False)
    for k, v in enumerate(cells):
        sp = s0.copy(); sp[v] += h
        sm = s0.copy(); sm[v] -= h
        fd[k] = (transport(sp)[0][1, 2] - transport(sm)[0][1, 2]) / (2 * h)
    err = np.max(np.abs(adj[cells] - fd) / np.abs(fd))
    say("## Way A: the adjoint compiler (full custom)\n")
    say(f"- adjoint Jacobian (flux times importance, two solves) versus "
        f"finite differences at 5 random cells: worst relative error "
        f"**{err:.1e}** (machine precision: the reactor perturbation "
        "formula, verified)")

    # ---- compile: (1) a feasible target exactly, (2) a silence demand ----
    def compile_target(G_star, zero_mask, mu, steps=1500):
        """Adam on logit parametrized survivals: s = S_MIN + range*sigmoid(t)."""
        rng_w = S_MAX - S_MIN
        t = np.zeros(V)
        m = np.zeros(V); v2 = np.zeros(V)
        hist = []
        for k in range(steps):
            sv = S_MIN + rng_w / (1 + np.exp(-t))
            L, g, G = loss_and_grad(sv, G_star, zero_mask, mu=mu)
            hist.append(L)
            dsdt = rng_w * np.exp(-t) / (1 + np.exp(-t)) ** 2
            gt = g * dsdt
            m = 0.9 * m + 0.1 * gt
            v2 = 0.999 * v2 + 0.001 * gt * gt
            mh = m / (1 - 0.9 ** (k + 1)); vh = v2 / (1 - 0.999 ** (k + 1))
            t -= 0.06 * mh / (np.sqrt(vh) + 1e-12)
        sv = S_MIN + rng_w / (1 + np.exp(-t))
        return sv, hist, transport(sv)[0]

    s_true = RNG.uniform(0.96, 0.999, V)
    G_seed = transport(s_true)[0]

    # (1) fidelity: recover a known feasible target
    no_kill = np.zeros((N_IN, N_OUT))
    s_fit, hist, G_fin = compile_target(G_seed, no_kill, mu=0.0)
    sig = G_seed > 0.05 * G_seed.max()
    rel = np.max(np.abs(G_fin[sig] - G_seed[sig]) / G_seed[sig])
    say(f"- **fidelity**: handed a feasible random 4 x 4 target and a blank "
        f"plate, the compiler recovers every significant weight to worst "
        f"error **{rel:.2%}** in 1500 Adam steps (final loss "
        f"{hist[-1]:.1e}), without ever being told the seed layout")

    # (2) the silence demand: partially infeasible on purpose, reported so
    offdiag = G_seed.copy(); np.fill_diagonal(offdiag, 0)
    ki, ko = np.unravel_index(np.argmax(offdiag), offdiag.shape)
    zero_mask = np.zeros((N_IN, N_OUT)); zero_mask[ki, ko] = 1.0
    G_star = G_seed * (1 - zero_mask)
    s_k, hist_k, G_k = compile_target(G_star, zero_mask, mu=25.0)
    supp = G_seed[ki, ko] / max(G_k[ki, ko], 1e-9)
    keep = (zero_mask == 0) & sig
    coll = np.max(np.abs(G_k[keep] - G_seed[keep]) / G_seed[keep])
    say(f"- **the silence demand**: killing one channel of a diffusive "
        f"fabric while preserving its neighbors is deliberately over "
        f"constrained (the paths overlap), and the compiler finds the "
        f"physical optimum of the trade: the loudest crosstalk channel "
        f"G[{ki+1},{ko+1}] suppressed **{supp:.0f}x** at a worst collateral "
        f"error of **{coll:.1%}** on the kept weights. Perfect isolation "
        f"wants collimation (Way B), and the compiler quantifies exactly "
        f"how much")
    # ---- Way B: the crossbar ----------------------------------------------
    say("## Way B: the crossbar (universal fabric)\n")
    G_fab = transport(np.full(V, S_MAX))[0]           # wide open fabric
    T = np.clip(G_star / np.maximum(G_fab, 1e-9), 0, 1)
    G_xbar = G_fab * T
    err_x = np.max(np.abs(G_xbar - G_star)[G_star > 0] / G_star[G_star > 0])
    say(f"- fabricate once wide open, program apertures per channel: "
        f"T = G*/G_fab elementwise; error **{err_x:.1e}** by construction "
        "for any target under the fabric ceiling. No optimization, "
        "instant reprogramming, at the price of dedicated sight lines "
        "(flux per channel falls as the channel count grows): the FPGA "
        "to Way A's full custom\n")

    # ---- Way C: SPSA through the wall --------------------------------------
    say("## Way C: self calibration through the wall (SPSA)\n")
    n_ph = 200_000
    def measured_loss(s_):
        G, _, _ = transport(s_)
        Gm = RNG.poisson(np.maximum(G, 0) * n_ph) / n_ph
        R = Gm - G_star
        return 0.5 * np.sum(R * R) + 2.0 * np.sum((Gm * zero_mask) ** 2)
    s = np.full(V, 0.99)
    spsa_hist = []
    a0, c0 = 4.0, 0.02
    for k in range(400):
        ck = c0 / (1 + k) ** 0.101
        ak = a0 / (1 + k) ** 0.602
        delta = RNG.choice([-1.0, 1.0], V)
        Lp = measured_loss(np.clip(s + ck * delta, S_MIN, S_MAX))
        Lm = measured_loss(np.clip(s - ck * delta, S_MIN, S_MAX))
        s = np.clip(s - ak * (Lp - Lm) / (2 * ck) * delta, S_MIN, S_MAX)
        if k % 5 == 0:
            spsa_hist.append((k, loss_and_grad(s, G_star, zero_mask)[0]))
    L_end = spsa_hist[-1][1]
    say(f"- two Poisson noisy measurements per step, all {V} trims "
        f"perturbed at once (Spall 1992): true loss falls from "
        f"{hist[0]:.2e} to **{L_end:.2e}** in 400 steps with no gradient, "
        "no model, and no penetration: this is how a sealed ampoule is "
        "trimmed onto its instance from outside the wall, under the "
        "machine's native noise\n")

    say("*Way A grinds the problem into the geometry, Way B rents a "
        "universal fabric, Way C tunes whatever was built using only "
        "the glow. A machine with a compiler is a computer; this one "
        "now has three.*")

    open(os.path.join(HERE, "compiler_results.md"), "w").write("\n".join(OUT))
    print("wrote transport/compiler_results.md")
    figure(hist, G_seed, G_fin, hist_k, G_k, zero_mask, spsa_hist)


def figure(hist, G_star, G_fin, hist_k, G_k, zero_mask, spsa_hist):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    INK, BLUE, RED, GREEN, AMBER, PURPLE, GREY = (
        "#16213e", "#2563eb", "#dc2626", "#16a34a",
        "#d97706", "#7c3aed", "#94a3b8")
    plt.rcParams.update({
        "figure.facecolor": "white", "axes.facecolor": "white",
        "savefig.facecolor": "white", "axes.edgecolor": INK,
        "axes.labelcolor": INK, "text.color": INK, "xtick.color": INK,
        "ytick.color": INK, "axes.titlecolor": INK, "font.size": 11,
        "axes.titlesize": 12, "axes.titleweight": "bold",
        "axes.grid": True, "grid.color": "#e5e7eb", "grid.linewidth": 0.8,
        "axes.spines.top": False, "axes.spines.right": False,
        "figure.dpi": 130, "svg.hashsalt": "nuclear-computer",
    })
    fig, (A, Bx, C) = plt.subplots(1, 3, figsize=(14.2, 4.5))

    A.semilogy(hist, color=BLUE, lw=2.2)
    A.set_xlabel("descent steps (adjoint gradient)")
    A.set_ylabel("compilation loss")
    A.set_title("A.  Way A: adjoint descent compiles the target")
    A.text(0.3, 0.55, "full Jacobian per step:\ntwo transport solves\n"
           "(flux × importance),\nverified to machine precision",
           transform=A.transAxes, fontsize=8.3, color=INK)

    idx = np.arange(N_IN * N_OUT)
    w = 0.4
    Bx.bar(idx - w/2, G_star.ravel(), w, color=GREY, label="target $G^*$")
    Bx.bar(idx + w/2, G_fin.ravel(), w, color=GREEN, label="compiled (fidelity)")
    kill = int(np.argmax(zero_mask.ravel()))
    Bx.bar(idx + w/2, G_k.ravel(), w*0.5, color=RED, alpha=0.6,
           label="silence run")
    Bx.annotate("demanded silent\n(crosstalk kill)", xy=(kill, 0.004),
                xytext=(kill + 1.2, 0.05), fontsize=8, color=RED,
                arrowprops=dict(arrowstyle="->", color=RED, lw=1.1))
    Bx.set_xlabel("weight matrix entry (input, output)")
    Bx.set_ylabel("port to port response")
    Bx.set_title("B.  Compiled weights: fidelity and silence runs")
    Bx.legend(frameon=False, fontsize=9)

    ks = [k for k, _ in spsa_hist]
    Ls = [l for _, l in spsa_hist]
    C.semilogy(ks, Ls, color=PURPLE, lw=2.2)
    C.set_xlabel("SPSA steps (two noisy measurements each)")
    C.set_ylabel("true compilation loss")
    C.set_title("C.  Way C: trimmed through the wall")
    C.text(0.3, 0.75, "no model, no gradient,\nno penetration: only\n"
           "Poisson counts of the glow", transform=C.transAxes,
           fontsize=8.3, color=INK)

    fig.suptitle("Figure 14.  The compiler, three ways",
                 fontsize=13, fontweight="bold", y=1.02)
    fig.tight_layout()
    for ext in ("svg", "png"):
        kw = {"metadata": {"Date": None}} if ext == "svg" else {}
        fig.savefig(os.path.join(FIGS, f"fig14_compiler.{ext}"),
                    bbox_inches="tight", **kw)
    print("wrote fig14_compiler")


if __name__ == "__main__":
    main()
