#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
The degree checker: a design rule tool for decay powered circuits.

Implements the homogenization procedure of theory Section 7.1. A circuit
is a tree of four node types over one source of activity lambda:

    THIN(x)     a thinned stream of rate x*lambda          degree 1
    AND(a, b)   coincidence, rate 2*tau_w*r_a*r_b          degree a+b
    ABS(a, p)   absorption, rate (1-p)*r_a                 degree a
    MUX(a,b,s)  s*r_a + (1-s)*r_b, requires equal degrees  degree a
    CMP(a, b)   comparator: decision r_a > r_b, requires equal degrees

check() labels every node's coincidence degree, flags every unequal
degree comparison (a latent aging defect), and homogenize() repairs a
flagged comparator by coinciding its lower degree side with reference
streams (full open thinnings) until degrees match.

The demonstration then does what the theorem promises: an inhomogeneous
comparator flips its decision when the source decays to half activity;
the repaired circuit holds its decision at every activity, verified both
analytically and by Poisson count simulation. Results are written to
degree_results.md.
"""
import os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
RNG = np.random.default_rng(57)          # seed honors Fe-57
TAU_W = 1e-6                             # coincidence window, s


# ---------------------------------------------------------------------------
# the circuit algebra
# ---------------------------------------------------------------------------
def THIN(x):
    return ("THIN", x)


def AND(a, b):
    return ("AND", a, b)


def ABS(a, p):
    return ("ABS", a, p)


def MUX(a, b, s):
    return ("MUX", a, b, s)


def rate(node, lam):
    kind = node[0]
    if kind == "THIN":
        return node[1] * lam
    if kind == "AND":
        return 2 * TAU_W * rate(node[1], lam) * rate(node[2], lam)
    if kind == "ABS":
        return (1 - node[2]) * rate(node[1], lam)
    if kind == "MUX":
        return node[3] * rate(node[1], lam) + (1 - node[3]) * rate(node[2], lam)
    raise ValueError(kind)


def degree(node, flags=None, path="root"):
    kind = node[0]
    if kind == "THIN":
        return 1
    if kind == "AND":
        return degree(node[1], flags, path + ".andL") + \
               degree(node[2], flags, path + ".andR")
    if kind == "ABS":
        return degree(node[1], flags, path + ".abs")
    if kind == "MUX":
        dA = degree(node[1], flags, path + ".muxL")
        dB = degree(node[2], flags, path + ".muxR")
        if dA != dB and flags is not None:
            flags.append((path, "MUX", dA, dB))
        return max(dA, dB)
    raise ValueError(kind)


def check_comparator(a, b):
    """Returns (degA, degB, flags) for the comparison a > b."""
    flags = []
    dA = degree(a, flags, "left")
    dB = degree(b, flags, "right")
    if dA != dB:
        flags.append(("comparator", "CMP", dA, dB))
    return dA, dB, flags


def homogenize(node, target_degree):
    """Raise node's degree to target by coinciding with reference streams
    (full open thinnings: semantically multiply by ~1, dimensionally +1)."""
    d = degree(node)
    while d < target_degree:
        node = AND(node, THIN(1.0))
        d += 1
    return node


# ---------------------------------------------------------------------------
# simulation: decide by Poisson counts, as hardware would
# ---------------------------------------------------------------------------
def simulate_decision(a, b, lam, T=100.0, trials=200):
    """Fraction of trials in which counted(a) > counted(b) over exposure T."""
    ra, rb = rate(a, lam), rate(b, lam)
    ca = RNG.poisson(ra * T, trials)
    cb = RNG.poisson(rb * T, trials)
    return float((ca > cb).mean())


def main():
    out = []

    def say(s=""):
        out.append(s)
        print(s)

    say("# Degree checker results (regenerated by degree_check.py)\n")
    say("The design rule of theory Section 7: compare like coincidence "
        "degree only with like. This tool labels degrees, flags "
        "violations, repairs them with reference stages, and shows by "
        "simulation what the violation costs.\n")

    lam0 = 5e5
    left = AND(THIN(0.8), THIN(0.9))          # degree 2
    right_bad = THIN(0.5)                     # degree 1: the defect
    dA, dB, flags = check_comparator(left, right_bad)
    say("## The defective circuit\n")
    say(f"Decision: AND(THIN 0.8, THIN 0.9)  >  THIN(0.5), at birth "
        f"activity {lam0:.0e}/s, window {TAU_W:.0e} s.\n")
    say(f"- degree(left) = {dA}, degree(right) = {dB}: "
        f"**{len(flags)} violation flagged** (mismatch {abs(dA-dB)})")

    right_fixed = homogenize(right_bad, dA)
    dA2, dB2, flags2 = check_comparator(left, right_fixed)
    say(f"- after homogenize(): right becomes AND(THIN 0.5, THIN 1.0); "
        f"degrees {dA2} = {dB2}, **{len(flags2)} flags**\n")

    say("## What the defect costs, and the repair buys\n")
    say("| activity | defective: analytic | defective: simulated "
        "| repaired: analytic | repaired: simulated |")
    say("|---|---|---|---|---|")
    for scale in (1.0, 0.5, 0.25):
        lam = lam0 * scale
        an_bad = "HIGH" if rate(left, lam) > rate(right_bad, lam) else "LOW"
        an_fix = "HIGH" if rate(left, lam) > rate(right_fixed, lam) else "LOW"
        mc_bad = simulate_decision(left, right_bad, lam)
        mc_fix = simulate_decision(left, right_fixed, lam)
        say(f"| {scale:.2f} λ₀ | {an_bad} | HIGH in {mc_bad:.0%} of trials "
            f"| {an_fix} | HIGH in {mc_fix:.0%} of trials |")
    say("")
    say("The defective comparator's decision inverts as the source "
        "decays (a degree 2 signal falls as the square); the repaired "
        "comparator, one reference stage later, is invariant at every "
        "activity, exactly as the degree homogeneity theorem requires. "
        "Run this check on every layout the way silicon runs design rule "
        "checks.\n")

    open(os.path.join(HERE, "degree_results.md"), "w").write("\n".join(out))
    print("wrote transport/degree_results.md")


if __name__ == "__main__":
    main()
